"""
IV Crush Avoidance Filter.

This is a *filter*, not a standalone strategy.  It should be applied to
signals generated by other strategies before order submission.

Problem
───────
Buying options into high implied volatility (especially before earnings)
exposes a trade to "IV crush" — a sharp drop in IV after the event that
destroys option value even if the underlying moves in the right direction.

Filter rules
────────────
1. Reject any signal within earnings_blackout_days of a known earnings date.
2. Reject if IV rank (IVR) of the underlying exceeds max_iv_rank_pre_earnings
   and an earnings event is pending within the blackout window.
3. Log the reason for every rejection.

Usage
─────
  filter = IVCrushFilter(params)
  clean_signals = filter.apply(signals, earnings_calendar, iv_ranks)
"""

from __future__ import annotations

import logging
from datetime import date, timedelta
from typing import Any, Dict, List, Optional

from .strategy_base import Signal

logger = logging.getLogger(__name__)


class IVCrushFilter:
    """
    Filters signals that are at high risk of IV crush.

    earnings_calendar : {symbol: [date, ...]} — known upcoming earnings dates.
    iv_ranks          : {symbol: float}       — current IV rank (0-100).
    """

    def __init__(self, params: Dict[str, Any] | None = None):
        params = params or {}
        self._blackout_days: int = params.get("earnings_blackout_days", 1)
        self._max_ivr: float = params.get("max_iv_rank_pre_earnings", 60)
        self._allow_earnings: bool = params.get("allow_earnings_trades", False)

    def apply(
        self,
        signals: List[Signal],
        earnings_calendar: Dict[str, List[date]] | None = None,
        iv_ranks: Dict[str, float] | None = None,
        reference_date: date | None = None,
    ) -> List[Signal]:
        """
        Return only signals that pass the IV crush check.

        Parameters
        ----------
        earnings_calendar : optional mapping of symbol → list of earnings dates.
        iv_ranks          : optional mapping of symbol → IV rank (0-100).
        reference_date    : date to use for 'today' (defaults to date.today()).
        """
        if self._allow_earnings:
            return signals

        today = reference_date or date.today()
        clean: List[Signal] = []

        for sig in signals:
            symbol = sig.symbol
            earnings_dates = (earnings_calendar or {}).get(symbol, [])
            ivr = (iv_ranks or {}).get(symbol)

            # Check earnings proximity
            near_earnings = any(
                abs((ed - today).days) <= self._blackout_days
                for ed in earnings_dates
            )

            if near_earnings:
                logger.info(
                    "IV crush filter: REJECTED %s %s — earnings within %d days",
                    symbol,
                    sig.direction,
                    self._blackout_days,
                )
                sig.metadata["iv_crush_filtered"] = True
                sig.metadata["iv_crush_reason"] = f"earnings within {self._blackout_days} days"
                continue

            # Check IV rank
            if ivr is not None and ivr > self._max_ivr and near_earnings:
                logger.info(
                    "IV crush filter: REJECTED %s — IV rank %.1f > max %.1f near earnings",
                    symbol,
                    ivr,
                    self._max_ivr,
                )
                sig.metadata["iv_crush_filtered"] = True
                sig.metadata["iv_crush_reason"] = f"IV rank {ivr:.1f} too high near earnings"
                continue

            clean.append(sig)

        rejected = len(signals) - len(clean)
        if rejected:
            logger.info("IV crush filter: %d/%d signals rejected", rejected, len(signals))

        return clean

    def is_near_earnings(
        self,
        symbol: str,
        earnings_calendar: Dict[str, List[date]],
        reference_date: date | None = None,
    ) -> bool:
        today = reference_date or date.today()
        for ed in earnings_calendar.get(symbol, []):
            if abs((ed - today).days) <= self._blackout_days:
                return True
        return False
