"""initial_ict_schema

Revision ID: e3b1441cd45f
Revises: 
Create Date: 2026-06-17 18:33:39.905369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b1441cd45f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.String(length=16), nullable=True),
    sa.Column('end_date', sa.String(length=16), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('is_approximate', sa.Boolean(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('report_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_strategy_id'), 'backtest_results', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_symbol'), 'backtest_results', ['symbol'], unique=False)
    op.create_table('ict_backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.String(length=16), nullable=True),
    sa.Column('end_date', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('long_win_rate', sa.Float(), nullable=True),
    sa.Column('short_win_rate', sa.Float(), nullable=True),
    sa.Column('avg_rr', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('monthly_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('strategy_params_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ict_backtest_results_status'), 'ict_backtest_results', ['status'], unique=False)
    op.create_index(op.f('ix_ict_backtest_results_symbol'), 'ict_backtest_results', ['symbol'], unique=False)
    op.create_index(op.f('ix_ict_backtest_results_task_id'), 'ict_backtest_results', ['task_id'], unique=True)
    op.create_table('ict_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('min_sweep_ticks', sa.Float(), nullable=True),
    sa.Column('rejection_candles', sa.Integer(), nullable=True),
    sa.Column('rejection_close_pct', sa.Float(), nullable=True),
    sa.Column('min_fvg_size', sa.Float(), nullable=True),
    sa.Column('fvg_fill_pct_entry', sa.Float(), nullable=True),
    sa.Column('fvg_lookback_bars', sa.Integer(), nullable=True),
    sa.Column('swing_lookback', sa.Integer(), nullable=True),
    sa.Column('equal_threshold_ticks', sa.Float(), nullable=True),
    sa.Column('sl_buffer_ticks', sa.Float(), nullable=True),
    sa.Column('exit_mode', sa.String(length=32), nullable=True),
    sa.Column('fixed_rr_ratio', sa.Float(), nullable=True),
    sa.Column('account_size', sa.Float(), nullable=True),
    sa.Column('risk_per_trade_pct', sa.Float(), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=True),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=True),
    sa.Column('trading_start_hour', sa.Integer(), nullable=True),
    sa.Column('stop_trading_hour', sa.Integer(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('asian_start_hour', sa.Integer(), nullable=True),
    sa.Column('asian_end_hour', sa.Integer(), nullable=True),
    sa.Column('london_start_hour', sa.Integer(), nullable=True),
    sa.Column('london_end_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ict_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('rr_achieved', sa.Float(), nullable=True),
    sa.Column('trade_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=16), nullable=True),
    sa.Column('fvg_type', sa.String(length=16), nullable=True),
    sa.Column('sweep_type', sa.String(length=32), nullable=True),
    sa.Column('backtest_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ict_trades_backtest_result_id'), 'ict_trades', ['backtest_result_id'], unique=False)
    op.create_index(op.f('ix_ict_trades_entry_time'), 'ict_trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_ict_trades_symbol'), 'ict_trades', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('option_symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('option_symbol', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_option_symbol'), 'positions', ['option_symbol'], unique=True)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('option_symbol', sa.String(length=64), nullable=True),
    sa.Column('check_name', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_option_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_ict_trades_symbol'), table_name='ict_trades')
    op.drop_index(op.f('ix_ict_trades_entry_time'), table_name='ict_trades')
    op.drop_index(op.f('ix_ict_trades_backtest_result_id'), table_name='ict_trades')
    op.drop_table('ict_trades')
    op.drop_table('ict_configs')
    op.drop_index(op.f('ix_ict_backtest_results_task_id'), table_name='ict_backtest_results')
    op.drop_index(op.f('ix_ict_backtest_results_symbol'), table_name='ict_backtest_results')
    op.drop_index(op.f('ix_ict_backtest_results_status'), table_name='ict_backtest_results')
    op.drop_table('ict_backtest_results')
    op.drop_index(op.f('ix_backtest_results_symbol'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_strategy_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
